[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/stats"
healthcheckTimeout = 300
restartPolicyType = "always"

[[services]]
name = "code-block-manager"

[services.variables]
PORT = "8000"
